### ISSUE TITLE
Skipping it.each tests?

### ISSUE THREAD

**Issue by darrennolan** [whitfin/it.each#3]
Is it possible to skip tests like a normal `it` test?

I don't seem to have any luck with it;  Doesn't appear to be a `it.each.skip` or a `it.skip.each` method.

**Comment by whitfin** [comment]
There isn't, sadly.

I can take a look at adding `it.each.skip`, it should be possible; unless you'd like to take a shot at it?

**Comment by jdavis61** [comment]
Hopefully https://github.com/whitfin/it.each/pull/6 is acceptable. Please review pull request and provide feedback.

**Comment by whitfin** [comment]
Closed by #6.
